apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-observability-to-frontend.yaml
  - allow-observability-to-backend.yaml
  - allow-observability-to-data.yaml
  - allow-frontend-to-observability.yaml
  - allow-backend-to-observability.yaml
  - allow-data-to-observability.yaml
