apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8saiaagentnoinlinesecrets.yaml
  - k8saiaagentrequiredannotations.yaml
  - k8saiaagentreadonlyrootfs.yaml
  - k8sdisallowlatest.yaml
  - k8srequiredlabels.yaml
  - k8srequiredresources.yaml
