apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-agent-no-inline-secrets.yaml
  - ai-agent-read-only-rootfs.yaml
  - ai-agent-required-annotations.yaml
  - disallow-latest.yaml
  - required-labels.yaml
  - required-resources.yaml
