apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-admin
  namespace: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-binding
  namespace: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulseguard-viewer
subjects:
  - kind: ServiceAccount
    name: viewer
    namespace: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulseguard-deployer
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding
  namespace: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulseguard-namespace-admin
subjects:
  - kind: ServiceAccount
    name: namespace-admin
    namespace: backend
